"""
This file contains lists of page titles.

"""
people = [
    'Douglas Adams',
    'Dante Alighieri',
    'Aristotle',
    'Emily Brontë',
    'Buddha',
    'Confucius',
    'Charles Darwin',
    'Charles Dickens',
    'Albert Einstein',
    'T. S. Eliot',
    'Ralph Waldo Emerson',
    'Richard Feynman',
    'Mahatma Gandhi',
    'Jesus',
    'John Keats',
    'Helen Keller',
    'John F. Kennedy',
    'Martin Luther King, Jr.',
    'Laozi',
    'Timothy Leary',
    'Muhammad',
    'Thomas Paine',
    'Eleanor Roosevelt',
    'Bertrand Russell',
    'William Saroyan',
    'William Shakespeare',
    'George Bernard Shaw',
    'Percy Bysshe Shelley',
    'Starhawk',
    'Leo Tolstoy',
    'Virgil',
    'Voltaire'
]

literary_works = [
    'Dune',
    'Fahrenheit 451',
    'Leaves of Grass',
    'The Little Prince',
    'The Lord of the Rings',
    '1984',
    'Paradise Lost',
    'Principia Discordia',
    'The Prophet',
    'Pride and Prejudice',
    'A Tale of Two Cities',
]

films = [
    'Casablanca',
    'Fight Club',
    'The Godfather',
    'Groundhog Day',
    'Harvey',
    'The Hours',
    'It\'s a Wonderful Life',
    'Life of Brian',
    'Magnolia',
    'The Matrix',
    'Memento',
    'One Flew Over the Cuckoo\'s Nest',
    'Schindler\'s List',
    'Star Wars',
    'Taxi Driver',
    'Three Days of the Condor',
    'United 93'
]

tv_shows = [
    'Babylon 5',
    'Blackadder',
    'Breaking Bad',
    'Buffy',
    'The Daily Show',
    'Game of Thrones',
    'Gilmore Girls',
    'Mad Men',
    'M*A*S*H',
    'Monty Python\'s Flying Circus',
    'MST3K',
    'Red Dwarf',
    'Seinfeld',
    'The Simpsons',
    'Star Trek',
    'The X-Files',
    'Twin Peaks',
    'The West Wing',
    'Wonderfalls'
]

themes = [
    'Ability',
    'Art',
    'Beauty',
    'Computers',
    'Courage',
    'Dance',
    'Drugs',
    'Education',
    'Film',
    'Flowers',
    'Friendship',
    'Hope',
    'Leadership',
    'Love',
    'Materialism',
    'Memory',
    'Politics',
    'Quotations',
    'Religion',
    'Science',
    'Sexuality',
    'Sports',
    'Success',
    'Television',
    'War'
]

places = [
    'Brazil',
    'California',
    'Canada',
    'China',
    'Cuba',
    'Europe',
    'France',
    'Germany',
    'India',
    'Iran',
    'Iraq',
    'Ireland',
    'Italy',
    'Japan',
    'London',
    'Mexico',
    'New York City',
    'North Korea',
    'Pakistan',
    'Russia',
    'South Korea',
    'Spain',
    'Sri Lanka',
    'Turkey',
    'United Kingdom',
    'Vietnam'
]